export const PlannerData = [
  {
    name: 'Ksenia Lidovich',
    position: 'Recruiter',
    nine: 'check',
    ninethirty: 'check',
    ten: 'check',
    tenthirty: 'check',
    eleven: 'available',
    eleventhirty: 'check',
    twelve: 'check',
    twelvethirty: 'check',
    thirteen: 'available',
    thirteenthirty: 'check',
    fourteen: 'check',
    fourteenthirty: 'available',
    fiveteen: 'check',
    fiveteenthirty: 'check',
    sixteen: 'available',
    sixteenthirty: 'check',
    seventeen: 'unavailable',
    seventeenthirty: 'check',
    eighteen: 'available',
    eighteenthirty: 'unavailable',
  },
  {
    name: 'Ksenia Lidovich',
    position: 'Recruiter',
    nine: 'check',
    ninethirty: 'check',
    ten: 'unavailable',
    tenthirty: 'check',
    eleven: 'unavailable',
    eleventhirty: 'check',
    twelve: 'available',
    twelvethirty: 'available',
    thirteen: 'available',
    thirteenthirty: 'unavailable',
    fourteen: 'check',
    fourteenthirty: 'check',
    fiveteen: 'check',
    fiveteenthirty: 'check',
    sixteen: 'unavailable',
    sixteenthirty: 'unavailable',
    seventeen: 'unavailable',
    seventeenthirty: 'check',
    eighteen: 'available',
    eighteenthirty: 'check',
  },
  {
    name: 'Ksedawd dwadawda',
    position: 'Recruiter',
    nine: 'check',
    ninethirty: 'unavailable',
    ten: 'unavailable',
    tenthirty: 'check',
    eleven: 'unavailable',
    eleventhirty: 'unavailable',
    twelve: 'check',
    twelvethirty: 'unavailable',
    thirteen: 'check',
    thirteenthirty: 'check',
    fourteen: 'check',
    fourteenthirty: 'unavailable',
    fiveteen: 'check',
    fiveteenthirty: 'unavailable',
    sixteen: 'available',
    sixteenthirty: 'available',
    seventeen: 'unavailable',
    seventeenthirty: 'check',
    eighteen: 'unavailable',
    eighteenthirty: 'check',
  },
  {
    name: 'adwda dwadaw ',
    position: 'Recruiter',
    nine: 'check',
    ninethirty: 'unavailable',
    ten: 'unavailable',
    tenthirty: 'check',
    eleven: 'unavailable',
    eleventhirty: 'check',
    twelve: 'available',
    twelvethirty: 'available',
    thirteen: 'available',
    thirteenthirty: 'unavailable',
    fourteen: 'check',
    fourteenthirty: 'available',
    fiveteen: 'check',
    fiveteenthirty: 'check',
    sixteen: 'check',
    sixteenthirty: 'available',
    seventeen: 'unavailable',
    seventeenthirty: 'check',
    eighteen: 'available',
    eighteenthirty: 'unavailable',
  },
  {
    name: 'aaaaaaaaaa bbbbbbbbbb',
    position: 'Recruiter',
    nine: 'check',
    ninethirty: 'unavailable',
    ten: 'unavailable',
    tenthirty: 'check',
    eleven: 'unavailable',
    eleventhirty: 'check',
    twelve: 'available',
    twelvethirty: 'available',
    thirteen: 'unavailable',
    thirteenthirty: 'unavailable',
    fourteen: 'check',
    fourteenthirty: 'available',
    fiveteen: 'check',
    fiveteenthirty: 'check',
    sixteen: 'check',
    sixteenthirty: 'unavailable',
    seventeen: 'available',
    seventeenthirty: 'check',
    eighteen: 'available',
    eighteenthirty: 'unavailable',
  },
];
